// generate XML for data widgets. should use data module....

var blocks = [
        [ 'Air', 'air' ],
        [ 'Stone', 'stone' ],
        [ 'Grass Block', 'grass' ],
        [ 'Dirt', 'dirt' ],
        [ 'Cobblestone', 'cobblestone' ],
        [ 'Wood Planks', 'planks' ],
        [ 'Sapling', 'sapling' ],
        [ 'Bedrock', 'bedrock' ],
        [ 'Water', 'flowing_water' ],
        [ 'Stationary Water', 'water' ],
        [ 'Lava', 'flowing_lava' ],
        [ 'Stationary Lava', 'lava' ],
        [ 'Sand', 'sand' ],
        [ 'Gravel', 'gravel' ],
        [ 'Gold Ore', 'gold_ore' ],
        [ 'Iron Ore', 'iron_ore' ],
        [ 'Coal Ore', 'coal_ore' ],
        [ 'Wood', 'log' ],
        [ 'Leaves', 'leaves' ],
        [ 'Sponge', 'sponge' ],
        [ 'Glass', 'glass' ],
        [ 'Lapis Lazuli Ore', 'lapis_ore' ],
        [ 'Lapis Lazuli Block', 'lapis_block' ],
        [ 'Dispenser', 'dispenser' ],
        [ 'Sandstone', 'sandstone' ],
        [ 'Note Block', 'noteblock' ],
        [ 'Bed', 'bed' ],
        [ 'Powered Rail', 'golden_rail' ],
        [ 'Detector Rail', 'detector_rail' ],
        [ 'Sticky Piston', 'sticky_piston' ],
        [ 'Cobweb', 'web' ],
        [ 'Grass', 'tallgrass' ],
        [ 'Dead Bush', 'deadbush' ],
        [ 'Piston', 'piston' ],
        [ 'Piston Head', 'piston_head' ],
        [ 'Wool', 'wool' ],
        [ 'Block moved by Piston', 'piston_extension' ],
        [ 'Dandelion', 'yellow_flower' ],
        [ 'Poppy', 'red_flower' ],
        [ 'Brown Mushroom', 'brown_mushroom' ],
        [ 'Red Mushroom', 'red_mushroom' ],
        [ 'Block of Gold', 'gold_block' ],
        [ 'Block of Iron', 'iron_block' ],
        [ 'Double Stone Slab', 'double_stone_slab' ],
        [ 'Stone Slab', 'stone_slab' ],
        [ 'Bricks', 'brick_block' ],
        [ 'TNT', 'tnt' ],
        [ 'Bookshelf', 'bookshelf' ],
        [ 'Moss Stone', 'mossy_cobblestone' ],
        [ 'Obsidian', 'obsidian' ],
        [ 'Torch', 'torch' ],
        [ 'Fire', 'fire' ],
        [ 'Monster Spawner', 'mob_spawner' ],
        [ 'Oak Wood Stairs', 'oak_stairs' ],
        [ 'Chest', 'chest' ],
        [ 'Redstone Wire', 'redstone_wire' ],
        [ 'Diamond Ore', 'diamond_ore' ],
        [ 'Block of Diamond', 'diamond_block' ],
        [ 'Crafting Table', 'crafting_table' ],
        [ 'Wheat', 'wheat' ],
        [ 'Farmland', 'farmland' ],
        [ 'Furnace', 'furnace' ],
        [ 'Burning Furnace', 'lit_furnace' ],
        [ 'Standing Sign', 'standing_sign' ],
        [ 'Oak Door', 'wooden_door' ],
        [ 'Ladder', 'ladder' ],
        [ 'Rail', 'rail' ],
        [ 'Cobblestone Stairs', 'stone_stairs' ],
        [ 'Wall Sign', 'wall_sign' ],
        [ 'Lever', 'lever' ],
        [ 'Stone Pressure Plate', 'stone_pressure_plate' ],
        [ 'Iron Door', 'iron_door' ],
        [ 'Wooden Pressure Plate', 'wooden_pressure_plate' ],
        [ 'Redstone Ore', 'redstone_ore' ],
        [ 'Glowing Redstone Ore', 'lit_redstone_ore' ],
        [ 'Redstone Torch (inactive)', 'unlit_redstone_torch' ],
        [ 'Redstone Torch (active)', 'redstone_torch' ],
        [ 'Stone Button', 'stone_button' ],
        [ 'Snow (layer)', 'snow_layer' ],
        [ 'Ice', 'ice' ],
        [ 'Snow', 'snow' ],
        [ 'Cactus', 'cactus' ],
        [ 'Clay', 'clay' ],
        [ 'Sugar Cane', 'reeds' ],
        [ 'Jukebox', 'jukebox' ],
        [ 'Fence', 'fence' ],
        [ 'Pumpkin', 'pumpkin' ],
        [ 'Netherrack', 'netherrack' ],
        [ 'Soul Sand', 'soul_sand' ],
        [ 'Glowstone', 'glowstone' ],
        [ 'Nether Portal', 'portal' ],
        [ "Jack o'Lantern", 'lit_pumpkin' ],
        [ 'Cake', 'cake' ],
        [ 'Redstone Repeater (inactive)', 'unpowered_repeater' ],
        [ 'Redstone Repeater (active)', 'powered_repeater' ],
        [ 'Stained Glass', 'stained_glass' ],
        [ 'Trapdoor', 'trapdoor' ],
        [ 'Monster Egg', 'monster_egg' ],
        [ 'Stone Bricks', 'stonebrick' ],
        [ 'Brown Mushroom (block)', 'brown_mushroom_block' ],
        [ 'Red Mushroom (block)', 'red_mushroom_block' ],
        [ 'Iron Bars', 'iron_bars' ],
        [ 'Glass Pane', 'glass_pane' ],
        [ 'Melon', 'melon_block' ],
        [ 'Pumpkin Stem', 'pumpkin_stem' ],
        [ 'Melon Stem', 'melon_stem' ],
        [ 'Vines', 'vine' ],
        [ 'Fence Gate', 'fence_gate' ],
        [ 'Brick Stairs', 'brick_stairs' ],
        [ 'Stone Brick Stairs', 'stone_brick_stairs' ],
        [ 'Mycelium', 'mycelium' ],
        [ 'Lily Pad', 'waterlily' ],
        [ 'Nether Brick', 'nether_brick' ],
        [ 'Nether Brick Fence', 'nether_brick_fence' ],
        [ 'Nether Brick Stairs', 'nether_brick_stairs' ],
        [ 'Nether Wart', 'nether_wart' ],
        [ 'Enchantment Table', 'enchanting_table' ],
        [ 'Brewing Stand', 'brewing_stand' ],
        [ 'Cauldron', 'cauldron' ],
        [ 'End Portal', 'end_portal' ],
        [ 'End Portal Block', 'end_portal_frame' ],
        [ 'End Stone', 'end_stone' ],
        [ 'Dragon Egg', 'dragon_egg' ],
        [ 'Redstone Lamp (inactive)', 'redstone_lamp' ],
        [ 'Redstone Lamp (active)', 'lit_redstone_lamp' ],
        [ 'Double Wooden Slab', 'double_wooden_slab' ],
        [ 'Wooden Slab', 'wooden_slab' ],
        [ 'Cocoa', 'cocoa' ],
        [ 'Sandstone Stairs', 'sandstone_stairs' ],
        [ 'Emerald Ore', 'emerald_ore' ],
        [ 'Ender Chest', 'ender_chest' ],
        [ 'Tripwire Hook', 'tripwire_hook' ],
        [ 'Tripwire', 'tripwire' ],
        [ 'Block of Emerald', 'emerald_block' ],
        [ 'Spruce Wood Stairs', 'spruce_stairs' ],
        [ 'Birch Wood Stairs', 'birch_stairs' ],
        [ 'Jungle Wood Stairs', 'jungle_stairs' ],
        [ 'Command Block', 'command_block' ],
        [ 'Beacon', 'beacon' ],
        [ 'Cobblestone Wall', 'cobblestone_wall' ],
        [ 'Flower Pot', 'flower_pot' ],
        [ 'Carrot', 'carrots' ],
        [ 'Potato', 'potatoes' ],
        [ 'Wooden Button', 'wooden_button' ],
        [ 'Mob head', 'skull' ],
        [ 'Anvil', 'anvil' ],
        [ 'Trapped Chest', 'trapped_chest' ],
        [ 'Weighted Pressure Plate (Light)', 'light_weighted_pressure_plate' ],
        [ 'Weighted Pressure Plate (Heavy)', 'heavy_weighted_pressure_plate' ],
        [ 'Redstone Comparator', 'unpowered_comparator' ],
        [ 'Redstone Comparator (deprecated)', 'powered_comparator' ],
        [ 'Daylight Sensor', 'daylight_detector' ],
        [ 'Block of Redstone', 'redstone_block' ],
        [ 'Nether Quartz Ore', 'quartz_ore' ],
        [ 'Hopper', 'hopper' ],
        [ 'Block of Quartz', 'quartz_block' ],
        [ 'Quartz Stairs', 'quartz_stairs' ],
        [ 'Activator Rail', 'activator_rail' ],
        [ 'Dropper', 'dropper' ],
        [ 'Stained Clay', 'stained_hardened_clay' ],
        [ 'Stained Glass Pane', 'stained_glass_pane' ],
        [ 'Leaves (Acacia/Dark Oak)', 'leaves2' ],
        [ 'Wood (Acacia/Dark Oak)', 'log2' ],
        [ 'Acacia Wood Stairs', 'acacia_stairs' ],
        [ 'Dark Oak Wood Stairs', 'dark_oak_stairs' ],
        [ 'Slime Block', 'slime' ],
        [ 'Barrier', 'barrier' ],
        [ 'Iron Trapdoor', 'iron_trapdoor' ],
        [ 'Prismarine', 'prismarine' ],
        [ 'Sea Lantern', 'sea_lantern' ],
        [ 'Hay Bale', 'hay_block' ],
        [ 'Carpet', 'carpet' ],
        [ 'Hardened Clay', 'hardened_clay' ],
        [ 'Block of Coal', 'coal_block' ],
        [ 'Packed Ice', 'packed_ice' ],
        [ 'Large Flowers', 'double_plant' ],
        [ 'Standing Banner', 'standing_banner' ],
        [ 'Wall Banner', 'wall_banner' ],
        [ 'Inverted Daylight Sensor', 'daylight_detector_inverted' ],
        [ 'Red Sandstone', 'red_sandstone' ],
        [ 'Red Sandstone Stairs', 'red_sandstone_stairs' ],
        [ 'Double Red Sandstone Slab', 'double_stone_slab2' ],
        [ 'Red Sandstone Slab', 'stone_slab2' ],
        [ 'Spruce Fence Gate', 'spruce_fence_gate' ],
        [ 'Birch Fence Gate', 'birch_fence_gate' ],
        [ 'Jungle Fence Gate', 'jungle_fence_gate' ],
        [ 'Dark Oak Fence Gate', 'dark_oak_fence_gate' ],
        [ 'Acacia Fence Gate', 'acacia_fence_gate' ],
        [ 'Spruce Fence', 'spruce_fence' ],
        [ 'Birch Fence', 'birch_fence' ],
        [ 'Jungle Fence', 'jungle_fence' ],
        [ 'Dark Oak Fence', 'dark_oak_fence' ],
        [ 'Acacia Fence', 'acacia_fence' ],
        [ 'Spruce Door', 'spruce_door' ],
        [ 'Birch Door', 'birch_door' ],
        [ 'Jungle Door', 'jungle_door' ],
        [ 'Acacia Door', 'acacia_door' ],
        [ 'Dark Oak Door', 'dark_oak_door' ]
      ]

console.log(`<?xml version="1.0" encoding="UTF-8"?>
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="factory_base" id="KeFSz*cyn|W)k[5BRqYC" deletable="false" movable="false" x="0" y="0">
    <mutation connections="LEFT" />
    <field name="NAME">data_block</field>
    <field name="INLINE">AUTO</field>
    <field name="CONNECTIONS">LEFT</field>
    <statement name="INPUTS">
      <block type="input_dummy" id=":JDy?V3Yb/2MR+Y_0q],">
        <field name="ALIGN">LEFT</field>
        <statement name="FIELDS">
          <block type="field_static" id="5s#r\`;Xy@nI5;Feb,I[Y">
            <field name="TEXT">block</field>
            <next>
              <block type="field_dropdown" id="pfx+fm,![}(*DwJ#52eM">
                <mutation options="${blocks.length}" />
                <field name="FIELDNAME">VALUE</field>
                ${blocks.map((b,i) =>{ return '<field name="USER'+i+'">'+b[0]+'</field>\n<field name="CPU'+i+'">'+b[1]+'</field>' }).join('\n')}
              </block>
            </next>
          </block>
        </statement>
      </block>
    </statement>
    <value name="OUTPUTTYPE">
      <block type="type_string" id="ZBo46jJ3hxv(|xIg7aJ|" />
    </value>
  </block>
</xml>`)

var instruments = [
        [ 'harp', 'harp' ],
        [ 'doubleBass', 'doubleBass' ],
        [ 'snareDrum', 'snareDrum' ],
        [ 'sticks', 'sticks' ],
        [ 'bassDrum', 'bassDrum' ]
      ]


console.log(`<xml xmlns="http://www.w3.org/1999/xhtml"><block type="factory_base" id="KeFSz*cyn|W)k[5BRqYC" deletable="false" movable="false" x="0" y="0"><mutation connections="LEFT"></mutation><field name="NAME">data_instrument</field><field name="INLINE">AUTO</field><field name="CONNECTIONS">LEFT</field><statement name="INPUTS"><block type="input_dummy" id=":JDy?V3Yb/2MR+Y_0q],"><field name="ALIGN">LEFT</field><statement name="FIELDS"><block type="field_static" id="5s#r\`;Xy@nI5;Feb,I[Y"><field name="TEXT">instrument</field><next><block type="field_dropdown" id="pfx+fm,![}(*DwJ#52eM"><mutation options="${instruments.length}"></mutation><field name="FIELDNAME">value</field>${instruments.map((instrument, i) => { return '<field name="USER'+i+'">'+instrument[0]+'</field><field name="CPU'+i+'">'+instrument[1]+'</field>' }).join('')} </block></next></block></statement></block></statement><value name="OUTPUTTYPE"><block type="type_string" id="ZXf#/=ql-vl+\`[IlC4Mr"></block></value></block></xml>`)


var items = [
        [ 'Iron Shovel', 'iron_shovel' ],
        [ 'Iron Pickaxe', 'iron_pickaxe' ],
        [ 'Iron Axe', 'iron_axe' ],
        [ 'Flint and Steel', 'flint_and_steel' ],
        [ 'Apple', 'apple' ],
        [ 'Bow', 'bow' ],
        [ 'Arrow', 'arrow' ],
        [ 'Coal', 'coal' ],
        [ 'Diamond', 'diamond' ],
        [ 'Iron Ingot', 'iron_ingot' ],
        [ 'Gold Ingot', 'gold_ingot' ],
        [ 'Iron Sword', 'iron_sword' ],
        [ 'Wooden Sword', 'wooden_sword' ],
        [ 'Wooden Shovel', 'wooden_shovel' ],
        [ 'Wooden Pickaxe', 'wooden_pickaxe' ],
        [ 'Wooden Axe', 'wooden_axe' ],
        [ 'Stone Sword', 'stone_sword' ],
        [ 'Stone Shovel', 'stone_shovel' ],
        [ 'Stone Pickaxe', 'stone_pickaxe' ],
        [ 'Stone Axe', 'stone_axe' ],
        [ 'Diamond Sword', 'diamond_sword' ],
        [ 'Diamond Shovel', 'diamond_shovel' ],
        [ 'Diamond Pickaxe', 'diamond_pickaxe' ],
        [ 'Diamond Axe', 'diamond_axe' ],
        [ 'Stick', 'stick' ],
        [ 'Bowl', 'bowl' ],
        [ 'Mushroom Stew', 'mushroom_stew' ],
        [ 'Golden Sword', 'golden_sword' ],
        [ 'Golden Shovel', 'golden_shovel' ],
        [ 'Golden Pickaxe', 'golden_pickaxe' ],
        [ 'Golden Axe', 'golden_axe' ],
        [ 'String', 'string' ],
        [ 'Feather', 'feather' ],
        [ 'Gunpowder', 'gunpowder' ],
        [ 'Wooden Hoe', 'wooden_hoe' ],
        [ 'Stone Hoe', 'stone_hoe' ],
        [ 'Iron Hoe', 'iron_hoe' ],
        [ 'Diamond Hoe', 'diamond_hoe' ],
        [ 'Golden Hoe', 'golden_hoe' ],
        [ 'Seeds', 'wheat_seeds' ],
        [ 'Wheat', 'wheat' ],
        [ 'Bread', 'bread' ],
        [ 'Leather Cap', 'leather_helmet' ],
        [ 'Leather Tunic', 'leather_chestplate' ],
        [ 'Leather Pants', 'leather_leggings' ],
        [ 'Leather Boots', 'leather_boots' ],
        [ 'Chain Helmet', 'chainmail_helmet' ],
        [ 'Chain Chestplate', 'chainmail_chestplate' ],
        [ 'Chain Leggings', 'chainmail_leggings' ],
        [ 'Chain Boots', 'chainmail_boots' ],
        [ 'Iron Helmet', 'iron_helmet' ],
        [ 'Iron Chestplate', 'iron_chestplate' ],
        [ 'Iron Leggings', 'iron_leggings' ],
        [ 'Iron Boots', 'iron_boots' ],
        [ 'Diamond Helmet', 'diamond_helmet' ],
        [ 'Diamond Chestplate', 'diamond_chestplate' ],
        [ 'Diamond Leggings', 'diamond_leggings' ],
        [ 'Diamond Boots', 'diamond_boots' ],
        [ 'Golden Helmet', 'golden_helmet' ],
        [ 'Golden Chestplate', 'golden_chestplate' ],
        [ 'Golden Leggings', 'golden_leggings' ],
        [ 'Golden Boots', 'golden_boots' ],
        [ 'Flint', 'flint' ],
        [ 'Raw Porkchop', 'porkchop' ],
        [ 'Cooked Porkchop', 'cooked_porkchop' ],
        [ 'Painting', 'painting' ],
        [ 'Golden Apple', 'golden_apple' ],
        [ 'Sign', 'sign' ],
        [ 'Oak Door', 'wooden_door' ],
        [ 'Bucket', 'bucket' ],
        [ 'Water Bucket', 'water_bucket' ],
        [ 'Lava Bucket', 'lava_bucket' ],
        [ 'Minecart', 'minecart' ],
        [ 'Saddle', 'saddle' ],
        [ 'Iron Door', 'iron_door' ],
        [ 'Redstone', 'redstone' ],
        [ 'Snowball', 'snowball' ],
        [ 'Boat', 'boat' ],
        [ 'Leather', 'leather' ],
        [ 'Milk', 'milk_bucket' ],
        [ 'Brick', 'brick' ],
        [ 'Clay', 'clay_ball' ],
        [ 'Sugar Cane', 'reeds' ],
        [ 'Paper', 'paper' ],
        [ 'Book', 'book' ],
        [ 'Slimeball', 'slime_ball' ],
        [ 'Minecart with Chest', 'chest_minecart' ],
        [ 'Minecart with Furnace', 'furnace_minecart' ],
        [ 'Egg', 'egg' ],
        [ 'Compass', 'compass' ],
        [ 'Fishing Rod', 'fishing_rod' ],
        [ 'Clock', 'clock' ],
        [ 'Glowstone Dust', 'glowstone_dust' ],
        [ 'Raw Fish', 'fish' ],
        [ 'Cooked Fish', 'cooked_fish' ],
        [ 'Dye', 'dye' ],
        [ 'Bone', 'bone' ],
        [ 'Sugar', 'sugar' ],
        [ 'Cake', 'cake' ],
        [ 'Bed', 'bed' ],
        [ 'Redstone Repeater', 'repeater' ],
        [ 'Cookie', 'cookie' ],
        [ 'Map', 'filled_map' ],
        [ 'Shears', 'shears' ],
        [ 'Melon', 'melon' ],
        [ 'Pumpkin Seeds', 'pumpkin_seeds' ],
        [ 'Melon Seeds', 'melon_seeds' ],
        [ 'Raw Beef', 'beef' ],
        [ 'Steak', 'cooked_beef' ],
        [ 'Raw Chicken', 'chicken' ],
        [ 'Cooked Chicken', 'cooked_chicken' ],
        [ 'Rotten Flesh', 'rotten_flesh' ],
        [ 'Ender Pearl', 'ender_pearl' ],
        [ 'Blaze Rod', 'blaze_rod' ],
        [ 'Ghast Tear', 'ghast_tear' ],
        [ 'Gold Nugget', 'gold_nugget' ],
        [ 'Nether Wart', 'nether_wart' ],
        [ 'Potion', 'potion' ],
        [ 'Glass Bottle', 'glass_bottle' ],
        [ 'Spider Eye', 'spider_eye' ],
        [ 'Fermented Spider Eye', 'fermented_spider_eye' ],
        [ 'Blaze Powder', 'blaze_powder' ],
        [ 'Magma Cream', 'magma_cream' ],
        [ 'Brewing Stand', 'brewing_stand' ],
        [ 'Cauldron', 'cauldron' ],
        [ 'Eye of Ender', 'ender_eye' ],
        [ 'Glistering Melon', 'speckled_melon' ],
        [ 'Spawn Egg', 'spawn_egg' ],
        [ "Bottle o' Enchanting", 'experience_bottle' ],
        [ 'Fire Charge', 'fire_charge' ],
        [ 'Book and Quill', 'writable_book' ],
        [ 'Written Book', 'written_book' ],
        [ 'Emerald', 'emerald' ],
        [ 'Item Frame', 'item_frame' ],
        [ 'Flower Pot', 'flower_pot' ],
        [ 'Carrot', 'carrot' ],
        [ 'Potato', 'potato' ],
        [ 'Baked Potato', 'baked_potato' ],
        [ 'Poisonous Potato', 'poisonous_potato' ],
        [ 'Empty Map', 'map' ],
        [ 'Golden Carrot', 'golden_carrot' ],
        [ 'Mob head', 'skull' ],
        [ 'Carrot on a Stick', 'carrot_on_a_stick' ],
        [ 'Nether Star', 'nether_star' ],
        [ 'Pumpkin Pie', 'pumpkin_pie' ],
        [ 'Firework Rocket', 'fireworks' ],
        [ 'Firework Star', 'firework_charge' ],
        [ 'Enchanted Book', 'enchanted_book' ],
        [ 'Redstone Comparator', 'comparator' ],
        [ 'Nether Brick', 'netherbrick' ],
        [ 'Nether Quartz', 'quartz' ],
        [ 'Minecart with TNT', 'tnt_minecart' ],
        [ 'Minecart with Hopper', 'hopper_minecart' ],
        [ 'Prismarine Shard', 'prismarine_shard' ],
        [ 'Prismarine Crystals', 'prismarine_crystals' ],
        [ 'Raw Rabbit', 'rabbit' ],
        [ 'Cooked Rabbit', 'cooked_rabbit' ],
        [ 'Rabbit Stew', 'rabbit_stew' ],
        [ "Rabbit's Foot", 'rabbit_foot' ],
        [ 'Rabbit Hide', 'rabbit_hide' ],
        [ 'Armor Stand', 'armor_stand' ],
        [ 'Iron Horse Armor', 'iron_horse_armor' ],
        [ 'Golden Horse Armor', 'golden_horse_armor' ],
        [ 'Diamond Horse Armor', 'diamond_horse_armor' ],
        [ 'Lead', 'lead' ],
        [ 'Name Tag', 'name_tag' ],
        [ 'Minecart with Command Block', 'command_block_minecart' ],
        [ 'Raw Mutton', 'mutton' ],
        [ 'Cooked Mutton', 'cooked_mutton' ],
        [ 'Banner', 'banner' ],
        [ 'Spruce Door', 'spruce_door' ],
        [ 'Birch Door', 'birch_door' ],
        [ 'Jungle Door', 'jungle_door' ],
        [ 'Acacia Door', 'acacia_door' ],
        [ 'Dark Oak Door', 'dark_oak_door' ],
        [ '13 Disc', 'record_13' ],
        [ 'Cat Disc', 'record_cat' ],
        [ 'Blocks Disc', 'record_blocks' ],
        [ 'Chirp Disc', 'record_chirp' ],
        [ 'Far Disc', 'record_far' ],
        [ 'Mall Disc', 'record_mall' ],
        [ 'Mellohi Disc', 'record_mellohi' ],
        [ 'Stal Disc', 'record_stal' ],
        [ 'Strad Disc', 'record_strad' ],
        [ 'Ward Disc', 'record_ward' ],
        [ '11 Disc', 'record_11' ],
        [ 'Wait Disc', 'record_wait' ]
      ]

console.log(`<?xml version="1.0" encoding="UTF-8"?>
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="factory_base" id="KeFSz*cyn|W)k[5BRqYC" deletable="false" movable="false" x="0" y="0">
    <mutation connections="LEFT" />
    <field name="NAME">data_item</field>
    <field name="INLINE">AUTO</field>
    <field name="CONNECTIONS">LEFT</field>
    <statement name="INPUTS">
      <block type="input_dummy" id=":JDy?V3Yb/2MR+Y_0q],">
        <field name="ALIGN">LEFT</field>
        <statement name="FIELDS">
          <block type="field_static" id="5s#r\`;Xy@nI5;Feb,I[Y">
            <field name="TEXT">item</field>
            <next>
              <block type="field_dropdown" id="pfx+fm,![}(*DwJ#52eM">
                <mutation options="${items.length}" />
                <field name="FIELDNAME">value</field>
                ${items.map((item, i) => { return '<field name="USER'+i+'">'+item[0]+'</field><field name="CPU'+i+'">'+item[1]+'</field>' })}
              </block>
            </next>
          </block>
        </statement>
      </block>
    </statement>
    <value name="OUTPUTTYPE">
      <block type="type_string" id="E!xRT+4ipaV9o.5hmav:" />
    </value>
  </block>
</xml>`)


